CREATE DATABASE IF NOT EXISTS jangmu;

USE jangmu;

CREATE TABLE IF NOT EXISTS words (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(255) NOT NULL,
    pronunciation VARCHAR(255) NOT NULL,
    pos VARCHAR(255) NOT NULL,
    meaning VARCHAR(255) NOT NULL,
    etymology VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fanqie (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fanqie VARCHAR(255) NOT NULL,
    shengmu BOOLEAN NOT NULL,
    reading VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
